// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'menu-link': string;
  'movieCard': string;
  'movieCard--content': string;
  'movieCard--img': string;
  'movieCard--tagline': string;
  'movieCard--title': string;
  'movieCard--titleYear': string;
  'movieCard--year': string;
  'movieCardMenu': string;
  'movieCardMenu--close': string;
}
export const cssExports: CssExports;
export default cssExports;
