// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'movieFilterBar': string;
  'movieFilterBar--arrow': string;
  'movieFilterBar--arrow-down': string;
  'movieFilterBar--genre': string;
  'movieFilterBar--genre-active': string;
  'movieFilterBar--genres': string;
  'movieFilterBar--sort': string;
  'movieFilterBar--sort-title': string;
  'movieFilterBar--sort-val': string;
}
export const cssExports: CssExports;
export default cssExports;
