// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'form': string;
  'form--buttons': string;
  'form--item': string;
  'form--row': string;
}
export const cssExports: CssExports;
export default cssExports;
