// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'movies--list': string;
  'movies--total': string;
  'movies--total-value': string;
}
export const cssExports: CssExports;
export default cssExports;
