// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'logo': string;
  'logo--bold': string;
  'logo--light': string;
}
export const cssExports: CssExports;
export default cssExports;
