// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'search-bar': string;
  'search-bar--content': string;
  'search-bar-btn': string;
}
export const cssExports: CssExports;
export default cssExports;
