// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checkbox-group': string;
  'checkbox-item': string;
  'checkbox-item--input': string;
  'checkbox-item--label': string;
  'input-toggle': string;
  'input-toggle--input': string;
  'input-toggle--opened': string;
}
export const cssExports: CssExports;
export default cssExports;
