// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'close': string;
  'modal': string;
  'modal--content': string;
  'modal--heading': string;
}
export const cssExports: CssExports;
export default cssExports;
